//***************************************************************************
//                                                                          *
// SPKRID, A Prototype Text-Dependent Speaker Identification System.        *
// Copyright (C) 2002 A.Sankaranarayanan.                                   *
//                                                                          *
// This file is part of SPKRID.                                             *
//                                                                          *
// SPKRID is free software; you can redistribute it and/or                  *
// modify it under the terms of the GNU General Public License              *
// as published by the Free Software Foundation; either version 2           *
// of the License, or (at your option) any later version.                   *
//                                                                          *
// This program is distributed in the hope that it will be useful,          *
// but WITHOUT ANY WARRANTY; without even the implied warranty of           *
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            *
// GNU General Public License for more details.                             *
//                                                                          *
// You should have received a copy of the GNU General Public License        *
// along with this program; if not, write to the Free Software              *
// Foundation, Inc., 59 Temple Place - Suite 330, Boston,                   *
// MA  02111-1307, USA.                                                     *
//                                                                          *
// My e-mail address is: total_nerd@hotmail.com.                            *
//                                                                          *
//                                                                          *
// PITCHEXTRACTOR.CPP                                                     	*
//                                                                          *
// Implementation of the PitchExtractor class which operates on one of      *
// the impulse generators generated by the ImpulseGenerator class.          *
//																			*
// Fundamental component of the Speaker Identification Project.            	*
//                                                                          *
// Last modified on February 21, 2002.                                      *
//                                                                          *
//***************************************************************************

#include <math.h>

#include "../../../globalconstants.hpp"
#include "../../../signal/signal.hpp"
#include "pitchextractor.hpp"

#define     NPITCHESTIMATES     6
#define     INITIAL_GUESS     0.005

//**********************************************************************************************
PitchExtractor::PitchExtractor (Signal& Train) : ITrain(Train) {
    PEstimate = new float [NPITCHESTIMATES];

    for (Current = 0; ITrain[Current] == 0.0; ++Current);

    AvgPitch = PEstimate[0] = PEstimate[1] =
        PEstimate[2] = INITIAL_GUESS;   // initial pitch guesstimate
}

//**********************************************************************************************
PitchExtractor::~PitchExtractor () {
    delete[] PEstimate;                 // get rid of pitch estimates
}

//**********************************************************************************************
float *PitchExtractor::PitchEstimateArray () {
    float BlankTime;                    // blanking interval
    float Decay;                        // exponential decay rate
    float Skipped;                      // approx. no. of samples skipped
    float Time;                         // time variable
    unsigned int Jump;                  // actual samples skipped
    unsigned int MaxJump;               // highest possible value
    float LatchedSample;

    if (Current >= ITrain.SampleCount ()) return (NULL);

    BlankTime = AvgPitch * 0.40;        // estimate blanking time
    Decay = AvgPitch / 0.695;           //   and decay
    Skipped = (BlankTime / SAMPLE_INTERVAL);
    Jump = (unsigned int) Skipped;      // initial skip value
    Time = (Jump - Skipped + 1) * SAMPLE_INTERVAL;

    MaxJump = ITrain.SampleCount () - Current;
    LatchedSample = ITrain[Current];

    for (; ((LatchedSample * exp(-Time / Decay)) >
           (ITrain[Current + Jump])) && (Jump < MaxJump);
           ++Jump, Time += SAMPLE_INTERVAL);

    Current += Jump;

    if (Jump < MaxJump) {               // if still in impulse train
	 	PEstimate[2] = PEstimate[1];
        PEstimate[1] = PEstimate[0];    // new pitch estimate
        PEstimate[0] = Jump * SAMPLE_INTERVAL;

		PEstimate[3] = PEstimate[0] + PEstimate[1];
		PEstimate[4] = PEstimate[1] + PEstimate[2];
        PEstimate[5] = PEstimate[0] +
            PEstimate[1] + PEstimate[2];

        AvgPitch = 0.5 * (AvgPitch +
            PEstimate[0]);              // average of prev. and curr. pitch

        if (AvgPitch > 0.010) AvgPitch = 0.010;
        if (AvgPitch < 0.004) AvgPitch = 0.004;

        return (PEstimate);             // was a success
    }

    return (NULL);                      // whoops! impulse train exhausted
}

//************************** PITCHEXTRACTOR.CPP ************************************************
